backend:
  name: git-gateway
  branch: main # تأكد أن هذا هو اسم الفرع في حسابك على جيت هاب

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }